### ISSUE TITLE
Installation problem: ImportError: cannot import name 'CallbackManager' from 'langchain.callbacks.base'

### ISSUE THREAD

**Issue by informatimago** [joshcho/ChatGPT.el#48]
The environment is:

$ distribution
Darwin 21.6.0  (macOS Monterey Version 12.6.3)
$ python --version
Python 3.10.11
$ pip --version
pip 23.1.1 from /opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip (python 3.10)

python an pip are from  MacPort.

```
21:22[pjb@despina org.xquartz:0 emacs 23Gi]$ pip install sexpdata==0.0.3 ; pip install epc ; pip install git+https://github.com/mmabrouk/chatgpt-wrapper ; chatgpt install
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sexpdata==0.0.3 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (0.0.3)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: epc in /Users/pjb/Library/Python/3.10/lib/python/site-packages (0.0.5)
Requirement already satisfied: sexpdata>=0.0.3 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from epc) (0.0.3)
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/mmabrouk/chatgpt-wrapper
  Cloning https://github.com/mmabrouk/chatgpt-wrapper to /private/var/folders/pq/82920zm125n09frk81rrtp200000gn/T/pip-req-build-j0is2qzb
  Running command git clone --filter=blob:none --quiet https://github.com/mmabrouk/chatgpt-wrapper /private/var/folders/pq/82920zm125n09frk81rrtp200000gn/T/pip-req-build-j0is2qzb
  Resolved https://github.com/mmabrouk/chatgpt-wrapper to commit 44755fff95f939d06ad4961d0b1409bdca114729
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: email-validator in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from chatGPT==0.8.4) (2.0.0.post2)
Requirement already satisfied: Flask in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from chatGPT==0.8.4) (2.3.2)
Requirement already satisfied: Jinja2 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from chatGPT==0.8.4) (3.1.2)
Requirement already satisfied: langchain>=0.0.123 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from chatGPT==0.8.4) (0.0.154)
Requirement already satisfied: names in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from chatGPT==0.8.4) (0.3.0)
Requirement already satisfied: openai>=0.27.2 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from chatGPT==0.8.4) (0.27.5)
Requirement already satisfied: openpyxl in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from chatGPT==0.8.4) (3.1.2)
Requirement already satisfied: playwright in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from chatGPT==0.8.4) (1.32.1)
Requirement already satisfied: prompt-toolkit in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from chatGPT==0.8.4) (3.0.38)
Requirement already satisfied: pydantic-computed in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from chatGPT==0.8.4) (0.2.1)
Requirement already satisfied: pyperclip in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from chatGPT==0.8.4) (1.8.2)
Requirement already satisfied: python-frontmatter in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from chatGPT==0.8.4) (1.0.0)
Requirement already satisfied: PyYAML in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from chatGPT==0.8.4) (6.0)
Requirement already satisfied: rich in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from chatGPT==0.8.4) (13.3.5)
Requirement already satisfied: sqlalchemy in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from chatGPT==0.8.4) (2.0.12)
Requirement already satisfied: tiktoken in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from chatGPT==0.8.4) (0.3.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from langchain>=0.0.123->chatGPT==0.8.4) (3.8.4)
Requirement already satisfied: async-timeout<5.0.0,>=4.0.0 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from langchain>=0.0.123->chatGPT==0.8.4) (4.0.2)
Requirement already satisfied: dataclasses-json<0.6.0,>=0.5.7 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from langchain>=0.0.123->chatGPT==0.8.4) (0.5.7)
Requirement already satisfied: numexpr<3.0.0,>=2.8.4 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from langchain>=0.0.123->chatGPT==0.8.4) (2.8.4)
Requirement already satisfied: numpy<2,>=1 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from langchain>=0.0.123->chatGPT==0.8.4) (1.24.3)
Requirement already satisfied: openapi-schema-pydantic<2.0,>=1.2 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from langchain>=0.0.123->chatGPT==0.8.4) (1.2.4)
Requirement already satisfied: pydantic<2,>=1 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from langchain>=0.0.123->chatGPT==0.8.4) (1.10.7)
Requirement already satisfied: requests<3,>=2 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from langchain>=0.0.123->chatGPT==0.8.4) (2.29.0)
Requirement already satisfied: tenacity<9.0.0,>=8.1.0 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from langchain>=0.0.123->chatGPT==0.8.4) (8.2.2)
Requirement already satisfied: tqdm>=4.48.0 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from langchain>=0.0.123->chatGPT==0.8.4) (4.65.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from sqlalchemy->chatGPT==0.8.4) (4.5.0)
Requirement already satisfied: greenlet!=0.4.17 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from sqlalchemy->chatGPT==0.8.4) (2.0.1)
Requirement already satisfied: dnspython>=2.0.0 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from email-validator->chatGPT==0.8.4) (2.3.0)
Requirement already satisfied: idna>=2.0.0 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from email-validator->chatGPT==0.8.4) (3.4)
Requirement already satisfied: Werkzeug>=2.3.3 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from Flask->chatGPT==0.8.4) (2.3.3)
Requirement already satisfied: itsdangerous>=2.1.2 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from Flask->chatGPT==0.8.4) (2.1.2)
Requirement already satisfied: click>=8.1.3 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from Flask->chatGPT==0.8.4) (8.1.3)
Requirement already satisfied: blinker>=1.6.2 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from Flask->chatGPT==0.8.4) (1.6.2)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from Jinja2->chatGPT==0.8.4) (2.1.1)
Requirement already satisfied: et-xmlfile in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from openpyxl->chatGPT==0.8.4) (1.1.0)
Requirement already satisfied: pyee==9.0.4 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from playwright->chatGPT==0.8.4) (9.0.4)
Requirement already satisfied: wcwidth in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from prompt-toolkit->chatGPT==0.8.4) (0.2.6)
Requirement already satisfied: setuptools<66.0.0,>=65.6.3 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from pydantic-computed->chatGPT==0.8.4) (65.7.0)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from rich->chatGPT==0.8.4) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from rich->chatGPT==0.8.4) (2.13.0)
Requirement already satisfied: regex>=2022.1.18 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from tiktoken->chatGPT==0.8.4) (2023.3.23)
Requirement already satisfied: attrs>=17.3.0 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain>=0.0.123->chatGPT==0.8.4) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain>=0.0.123->chatGPT==0.8.4) (3.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain>=0.0.123->chatGPT==0.8.4) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain>=0.0.123->chatGPT==0.8.4) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain>=0.0.123->chatGPT==0.8.4) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain>=0.0.123->chatGPT==0.8.4) (1.3.1)
Requirement already satisfied: marshmallow<4.0.0,>=3.3.0 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from dataclasses-json<0.6.0,>=0.5.7->langchain>=0.0.123->chatGPT==0.8.4) (3.19.0)
Requirement already satisfied: marshmallow-enum<2.0.0,>=1.5.1 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from dataclasses-json<0.6.0,>=0.5.7->langchain>=0.0.123->chatGPT==0.8.4) (1.5.1)
Requirement already satisfied: typing-inspect>=0.4.0 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from dataclasses-json<0.6.0,>=0.5.7->langchain>=0.0.123->chatGPT==0.8.4) (0.8.0)
Requirement already satisfied: mdurl~=0.1 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich->chatGPT==0.8.4) (0.1.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from requests<3,>=2->langchain>=0.0.123->chatGPT==0.8.4) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from requests<3,>=2->langchain>=0.0.123->chatGPT==0.8.4) (2022.12.7)
Requirement already satisfied: packaging>=17.0 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from marshmallow<4.0.0,>=3.3.0->dataclasses-json<0.6.0,>=0.5.7->langchain>=0.0.123->chatGPT==0.8.4) (23.1)
Requirement already satisfied: mypy-extensions>=0.3.0 in /Users/pjb/Library/Python/3.10/lib/python/site-packages (from typing-inspect>=0.4.0->dataclasses-json<0.6.0,>=0.5.7->langchain>=0.0.123->chatGPT==0.8.4) (1.0.0)
 Traceback (most recent call last):
  File "/Users/pjb/Library/Python/3.10/bin/chatgpt", line 5, in <module>
    from chatgpt_wrapper.main import main
  File "/Users/pjb/Library/Python/3.10/lib/python/site-packages/chatgpt_wrapper/__init__.py", line 1, in <module>
    from chatgpt_wrapper.backends.openai.api import OpenAIAPI
  File "/Users/pjb/Library/Python/3.10/lib/python/site-packages/chatgpt_wrapper/backends/openai/api.py", line 10, in <module>
    from chatgpt_wrapper.core.backend import Backend
  File "/Users/pjb/Library/Python/3.10/lib/python/site-packages/chatgpt_wrapper/core/backend.py", line 4, in <module>
    from langchain.callbacks.base import CallbackManager
ImportError: cannot import name 'CallbackManager' from 'langchain.callbacks.base' (/Users/pjb/Library/Python/3.10/lib/python/site-packages/langchain/callbacks/base.py)
```

**Comment by gj313** [comment]
I had the same problem, waiting for help.

**Comment by gj313** [comment]
I found that it may be the reason of the langchain version. 
With an older version of langchain, 
   pip install langchain==0.0.153
the problem disappeared.

**Comment by joshcho** [comment]
This is most likely a [chatgpt-wrapper](https://github.com/mmabrouk/chatgpt-wrapper/issues) issue. If the issue persists, please post there.
